import Logo from './BYC LOGO JPG FILE 1.png'
import SubImageLeft from './Frame 180.png'
import SubImageCenter from './Frame 179.png'
import SubImageRight from './Frame 181.png'
import NewImageLeft from './Frame 42.png'
import NewImageCenter from './Frame 41 (1).png'
import NewImageRight from './Frame 34.png'
import CollectionImageRight from './Frame 166 (1).png'
import CollectionButtomLeft from './Frame 167.png'
import CollectionButtomRight from './Frame 168.png'
import Underline from './Underline.png'
import WomenPantsLeft from './Womenpants1.png'
import WomenPantsCenter from './Womenpants2.png'
import WomenPantsRight from './Womenpants3.png'
import NavArrowLeft from './Navarrowleft.png'
import NavArrowRight from './Navarrowright.png'
import BlogImageLeft from './Blogimg1.png'
import BlogImageCenter from './Blogimg2.png'
import BlogImageRight from './Blogimg3.png'
import AuthorImage from './Authorimg.png'
import ReadMoreArrow from './Readmorearrow.png'
import Paypal from './PayPal.png'
import Visa from './Visa.png'
import Mastercard from './MasterCard.png'
import NewsLetterArrow from './NewsLetterArrow.png'
import Mail from './Mail.png'
import Phone from './Phone.png'
import Facebook from './Facebook.png'
import X from './X.png'
import Instagram from './Instagram.png'
import Youtube from './Youtube.png'
import HR from './HR.png'
import BlogsImage from './BlogsImage.png'
import Aboutus from './Aboutus.png'
import AwardsMedal from './AwardsMedal.png'
import BycMenBoxers from './BycMenBoxers.png'
import Map from './Map.png'
import AddressIcon from './AddressIcon.png'
import PhoneCallIcon from './PhoneCallIcon.png'
import EmailIcon from './EmailIcon.png'
import Bycboxerswine from './Bycboxerswine.png'
import Bycboxersblue from './Bycboxersblue.png'
import SecuredPayImage from './SecuredPayImage.png'
import Divider from './Divider.png'

export {Logo, SubImageLeft, SubImageCenter, SubImageRight, NewImageLeft, NewImageCenter, NewImageRight, CollectionImageRight, CollectionButtomLeft, CollectionButtomRight, Underline, WomenPantsLeft, WomenPantsCenter, WomenPantsRight, NavArrowLeft, NavArrowRight, BlogImageLeft, BlogImageCenter, BlogImageRight, AuthorImage, ReadMoreArrow, Paypal, Visa, Mastercard, NewsLetterArrow, Mail, Phone, Facebook, X, Instagram, Youtube, HR, BlogsImage, Aboutus, AwardsMedal, BycMenBoxers, Map, AddressIcon, PhoneCallIcon, EmailIcon, Bycboxersblue, Bycboxerswine, SecuredPayImage, Divider};